org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

### Mod properties ###
mod_version=1.0.0
maven_group=com.furimoe
archives_name=neko-whitelist
enabled_platforms=fabric,neoforge

### Architectury ###
architectury_loom_version=1.17.491
architectury_plugin_version=3.5.170
shadow_version=8.3.6

### Minecraft ###
minecraft_version=26.2
java_version=25

### Loaders ###
fabric_loader_version=0.19.3
fabric_api_version=0.161.0+26.2
neoforge_version=26.2.0.88

### Architectury API ###
architectury_api_version=21.1.10
