org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

### Mod properties ###
mod_version=1.0.0
maven_group=com.furimoe
archives_name=neko-whitelist
enabled_platforms=fabric,neoforge

### Architectury ###
architectury_loom_version=1.13.467
architectury_plugin_version=3.5.170
shadow_version=8.3.6

### Minecraft ###
minecraft_version=1.21.4
java_version=21

### Loaders ###
fabric_loader_version=0.19.5
fabric_api_version=0.119.4+1.21.4
neoforge_version=21.4.157

### Architectury API ###
architectury_api_version=15.0.3
